- name: Vision One Container Security Scan Action
  uses: trendmicro/tmas-scan-action@version*
   with:
      # Mandatory
      TMAS_API_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaWQiOiJmYzcwYjEwMi00YWM5LTQyZjktYWQ5Ni1hM2IyMGIwMWYwYTkiLCJjcGlkIjoic3ZwIiwicHBpZCI6ImN1cyIsIml0IjoxNzM4NTY4MTIwLCJldCI6MTc3MDEwNDExOSwiaWQiOiI3ZDk1NGI0Ni03NTJjLTQ5NzQtYWI0Zi1mOGZhZDk3YjJjOGQiLCJ0b2tlblVzZSI6ImN1c3RvbWVyIn0.YATsobnUUIeufJxWRogX21m85gR0EeGGrUHh41H7ANJC59poC7PNbah_EXcVF3an22KNUiTOkRqz-aquMDfXibmN4S2vd8G44IzGf3gf2DSi_iea9_uo0QHCv1FHQIuMrouMTqaT1ZV0nrsGahktj4BbJrJo-q6o99uYcrhONkT8LKLGfeafwREcE6kWu6Xfc0kZ37BW6_MuDt3tL7E97vY2iL_9qYVTzWCd9xKIIvqn_iZbR1HRUEth5goBXEtcZnOSSZP0hZU_feTdS_wiDQMIlRqthLndGgXkexlr4mb5SX-ZVz0pXW-d534h-ng30lVrHaD-2Re79umtgYPwVHuDV662Wlb--BykWNVaYb7ecHMK44Jz9UW8DGKMoQndAXT6syPAIq30ZHqb6F-kl-CvpSNQ08fqyq2Ekj6GEE0gqb6B9JY1-VLDizoiD51ZnJE4jsHq3vI5UNoHVYJwBHzsaipocKEIWHpYjamfZYDTcFVbMf0VsL7d93UsQ6In46g35L7ciCwq-ftJErF9t6xjxr2z7BcY1ACwGKC6c517WcDZ-5kaGrpIgyiWuAUcEOE9jpdknT6QtlHeE2ItdZx_OSSV5jIlHDULNt8PphWpYjfMPb-XQIuMdR10iygQOhj1K6jWXeB5ECaM4iMjDly6voZcVdOzpnutx1Is6R4
      REGION: us-east-1
      VULNERABILITY_SCAN: true
      # Optional
      SBOM: true # Saves SBOM to SBOM.json so you can export it as an artifact later.
      MALWARE_SCAN: true # Enable malware scan.
      SECRETS_SCAN: true # Enable secrets scan.
      IMAGE: alpine # The image need to be public or the pipeline need to have access to the private image of choice.
      LOCAL_IMAGE_TARBALL: image.tar
      # For each threshold below, select the maximum number of vulnerabilities that are acceptable.
      MAX_TOTAL: 0
      MAX_CRITICAL: 0
      MAX_HIGH: 0
      MAX_MEDIUM: 0
      MAX_LOW: 0
      MAX_NEGLIGIBLE: 0
      MAX_UNKNOWN: 0
      SCAN_RESULT_ARTIFACT: result.json # Save as an artifact in GitHub to be able to keep the result of the scan.
