- name: Vision One Container Security Scan Action
  uses: trendmicro/tmas-scan-action@version*
   with:
      # Mandatory
      TMAS_API_KEY: ${{ secrets.eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjaWQiOiIxOTZiMGU2Ny1iODVmLTQ5MWEtOTNhMy05YWIwOWRiZTQ3MDIiLCJjcGlkIjoic3ZwIiwicHBpZCI6ImN1cyIsIml0IjoxNzI5NjkwMTY0LCJldCI6MTc2MTIyNjE2NCwiaWQiOiI3ZmZjMmIzZi0wNzZiLTQ1MDUtOGI1YS05YTU4Mjc0YWJlNGQiLCJ0b2tlblVzZSI6ImN1c3RvbWVyIn0.H9Pd4qJ8-9HS_DqoYWxgf1BBI17zlxH-F9AY0lPSU1mfU26-dmt_hKNqLofPgIV3i5FV2-y8Ri1pgxwBknDa_nshFLC6XkS3j7G1GprKORDbfKdizpRn2mRLqKJdPdK9Z6WRPm9vKEa-i48K7ubF541S1akgrdeB9-PneveygEzsK4kQ_aS09Pt__xUrhMdCqvD_dxjaLlS4WTlXJVte273wG-d9xc0ql3t5nx0Jz0646Wq8XPUMNdBFNDXGc_WObeR04waxZr2QTirTrCyrvbpPs8wIgRUEiL3sjUC_VcXBN1ghVQ8RTekr9oNz3kZ-Im828TDOZAywyIocx_X9kijb5STBhyNmsals2X_FZEgUW62vJtsO5zD5loZv7ue9WrA6iYbiyXFbqtI6iv4tprgDP14KNi66kiBDxu6DYVTle2N0G-5YZZTzC9bHIE2IphpXs1VvIk8Sd_1C6lRXmeeS3vQtn-YtqWQx0Qq2w67swJWTHSjGtgYxhHriCzBi9Igg8zBkr2-qxPCLKaBBZEfjyV3VJldXLn5BBHUKcoZ5Hm28NarMrKYEDpSAJOG0Vfc3ANasNrJYNpCUZ4ABCXbfxzVMMKtHGyX1nYZVkWW6Ee23OiiZjh0dJdM8mKzFdi2N2cDKZbzePWQbMorv61PYG-Bcc6HLPOkBsVdWwt4 }}
      REGION: ap-southeast-2
      VULNERABILITY_SCAN: true
      # Optional
      SBOM: true # Saves SBOM to SBOM.json so you can export it as an artifact later.
      MALWARE_SCAN: true # Enable malware scan.
      SECRETS_SCAN: true # Enable secrets scan.
      IMAGE: alpine # The image need to be public or the pipeline need to have access to the private image of choice.
      LOCAL_IMAGE_TARBALL: image.tar
      # For each threshold below, select the maximum number of vulnerabilities that are acceptable.
      MAX_TOTAL: 0
      MAX_CRITICAL: 0
      MAX_HIGH: 0
      MAX_MEDIUM: 0
      MAX_LOW: 0
      MAX_NEGLIGIBLE: 0
      MAX_UNKNOWN: 0
      SCAN_RESULT_ARTIFACT: result.json # Save as an artifact in GitHub to be able to keep the result of the scan.
